# Generated by Django 4.1.2 on 2022-10-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('drive', 'drive'), ('bike', 'bike'), ('walk', 'walk')], default='drive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('u_counts', models.PositiveIntegerField(default=0)),
                ('e_time', models.TimeField(null=True)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='course.point')),
                ('layover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layover', to='course.point')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='course.point')),
            ],
        ),
    ]
