# Generated by Django 4.1.2 on 2022-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
