# Generated by Django 4.1.2 on 2022-10-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_description_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='course',
            name='layover',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start',
        ),
        migrations.AddField(
            model_name='point',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='course.course'),
        ),
        migrations.AddField(
            model_name='point',
            name='idx',
            field=models.SmallIntegerField(default=0),
        ),
    ]
