# Generated by Django 4.1.2 on 2022-10-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_destination_remove_course_layover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='course.course'),
        ),
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='idx',
            field=models.SmallIntegerField(),
        ),
    ]
