# Generated by Django 4.1.2 on 2022-11-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_point_course_alter_point_id_alter_point_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='point',
            name='pid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
