# Generated by Django 4.1.2 on 2022-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_point_name_point_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
