# Generated by Django 4.1.2 on 2022-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("course", "0005_remove_course_tag_course_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(related_name="courses", to="tag.tag"),
        ),
    ]
