# Generated by Django 4.1.2 on 2022-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_point_latitude_alter_point_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='pid',
        ),
        migrations.AddField(
            model_name='point',
            name='category',
            field=models.CharField(choices=[('path', 'path'), ('marker', 'marker')], default='marker', max_length=10),
        ),
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
