# Generated by Django 4.1.2 on 2022-11-29 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_course_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="hours",
            field=models.SmallIntegerField(default=18),
        ),
    ]
