dist: bionic

jobs:
  include:
    - language: node_js
      node_js: 14
      python: "3.7.9"
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "uYTKi2cA3BsO04RZms+SJ1DFFvACIVODGzekspSg7EtXPKtRSXo8DszQimSokSH3pkE7V2OaoQhFJ46iueN4/QydAPFI8upJk7y27GzLoDbvtE4186BLxKH34wceFVw2Ve/ZQSV89zS68yxrLRQLWKKCvanOYhz4+CjJQW8RRggdQiVzsWCAfVhvVJaBfmnGMhHMcZXbp15OPqfYnpAZrbZD5ZppkPFsVwAAGt+C9ZU2Ij6nT9AtgKmpaUXvQ5k9VhxKomsRNe8eUdzSa2wlx9ERZkLKxAjLuftDi5Jx24Ct7EXI79kpZsW+AzR0M5lhqFKkmM11MAajd3jPOED9NC2JQee7drLklqAp61KC/d2vr/5pUwgWeIhPSAG/rd/aBDLORYHWUJ64FWsCKpM8iSxlIYM/lBiOeC4rsRT1T8DaNet5bVqQwKgglTMeDN2QUv0jazDnzJmftFbWaDOQJOi/JSQrFH++J6AGipAA8l9L3xsF8447VPkWHH/OJetA6LTHgSRyOVtOLrtDz6sP+mXFIYLOb0IhxZx23sGTl1H9/wT2aH3z51S4AjJUSbFzMck/dqgIA0LaeRnhVNsQEFpI1IWVcMh7L8InSJ0bxJrYEBX7ckayZjj+/b+OErrbGtKKuoHpSvbzaiY/gYMjT6WKYEgbzNmvrbRdht3tAnM="
      install:
        - source ~/virtualenv/python3.7/bin/activate
        - cd backend/team12
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - cd ../../frontend
        - yarn install
        - pip install coveralls
        - yarn global add coveralls
        - gem install coveralls-lcov
      script:
        # - ./node_modules/.bin/eslint src (cd .. ?)
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ../backend/team12
        # - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - sonar-scanner
        - coveralls --merge=../../frontend/coverage.json
      
