dist: bionic

jobs:
  include:
    - language: node_js
      node_js: 14
      python: "3.7.9"
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: 
      install:
        - source ~/virtualenv/python3.7/bin/activate
        - cd backend/team12
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - cd ../../frontend
        - yarn install
        - pip install coveralls
        - yarn global add coveralls
        - gem install coveralls-lcov
      script:
        # - ./node_modules/.bin/eslint src (cd ?)
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ../backend/team12
        - black .
        - pylint **/*.py
        - coverage run --source='.' manage.py test
        - coverage xml
        # - cd ../..
        # - sonar-scanner
        - coveralls --merge=../../frontend/coverage.json
      
