# Generated by Django 4.1.2 on 2022-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="tag.tag"),
        ),
    ]
