# Generated by Django 4.1.2 on 2022-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "male"), ("F", "female")], max_length=10
            ),
        ),
    ]
