# Generated by Django 4.1.2 on 2022-11-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth",
        ),
        migrations.AddField(
            model_name="user",
            name="ages",
            field=models.SmallIntegerField(default=20),
        ),
    ]
